### ISSUE TITLE
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by eponraj27392** [lopatovsky/HMMs#13]
I have been using `google colab`. I would like to work with Hidden markov, so I would like to install a library called `hmms `On installing `pip install hmms`, i received the following error.

> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I also try to install the same library in `Pycharm IDE`, I received the same error with some call backs.

> Command "python setup.py egg_info" failed with error code 1 in C:\Users\eponr\AppData\Local\Temp\pycharm-packaging\hmms\

```
Collecting hmms
  Using cached https://files.pythonhosted.org/packages/e9/e4/c070c44ec8a391f6d5501316d1ed7615058f1fd365ff4ed65c9636d0bf62/hmms-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\eponr\AppData\Local\Temp\pycharm-packaging\hmms\setup.py", line 22, in <module>
        ext_modules=cythonize(glob.glob('hmms/*.pyx'), language_level=3, include_dirs=[numpy.get_include()]),
      File "C:\Users\eponr\PycharmProjects\untitled1\venv\lib\site-packages\Cython\Build\Dependencies.py", line 955, in cythonize
        c_options = CompilationOptions(**options)
      File "C:\Users\eponr\PycharmProjects\untitled1\venv\lib\site-packages\Cython\Compiler\Main.py", line 563, in __init__
        raise ValueError(message)
    ValueError: got unknown compilation option, please remove: include_dirs


What does it means and how can i rectify this issue ? kindly suggest some solution to get working
```

**Comment by mohammeddanishkhan** [comment]
> I have been using `google colab`. I would like to work with Hidden markov, so I would like to install a library called `hmms `On installing `pip install hmms`, i received the following error.
> 
> > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> 
> I also try to install the same library in `Pycharm IDE`, I received the same error with some call backs.
> 
> > Command "python setup.py egg_info" failed with error code 1 in C:\Users\eponr\AppData\Local\Temp\pycharm-packaging\hmms\
> 
> ```
> Collecting hmms
>   Using cached https://files.pythonhosted.org/packages/e9/e4/c070c44ec8a391f6d5501316d1ed7615058f1fd365ff4ed65c9636d0bf62/hmms-0.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\eponr\AppData\Local\Temp\pycharm-packaging\hmms\setup.py", line 22, in <module>
>         ext_modules=cythonize(glob.glob('hmms/*.pyx'), language_level=3, include_dirs=[numpy.get_include()]),
>       File "C:\Users\eponr\PycharmProjects\untitled1\venv\lib\site-packages\Cython\Build\Dependencies.py", line 955, in cythonize
>         c_options = CompilationOptions(**options)
>       File "C:\Users\eponr\PycharmProjects\untitled1\venv\lib\site-packages\Cython\Compiler\Main.py", line 563, in __init__
>         raise ValueError(message)
>     ValueError: got unknown compilation option, please remove: include_dirs
> 
> 
> What does it means and how can i rectify this issue ? kindly suggest some solution to get working
> ```

Hey, did you find any solution to this problem?

**Comment by eponraj27392** [comment]
No

Regards / Yours sincerely

---------------------------------------------------------------

Esakkiponraj Esakkimuthu

e-Mail:   eponraj27392@gmail.com

---------------------------------------------------------------

*$$$ The race has not yet over bcoz I haven't won yet** $$$*

**Comment by shahab-anjum** [comment]
i also got the same issue so plz help me

**Comment by shahab-anjum** [comment]
i need hmm in my thesis so if u?

**Comment by eponraj27392** [comment]
I too had the same problem of implementing HMM in my thesis.
I found some solutions given by Lazy programmer tutorial for Hidden Markov
model solves my problem.
But he develop the HMM model from the scratch using some DL frameworks..
Better you can go with that option, since hmms and hmmlearn library doesn't
support continuous data.




Regards / Yours sincerely

---------------------------------------------------------------

Esakkiponraj Esakkimuthu

e-Mail:   eponraj27392@gmail.com

---------------------------------------------------------------

*$$$ The race has not yet over bcoz I haven't won yet** $$$*

**Comment by medh61** [comment]
You install the library  hmms from github; and the problem will be solved
The command is :
!python -m pip install git+https://github.com/lopatovsky/HMM
Duplicate of #s#egg=HMMs

**Comment by medh61** [comment]
You install the library hmms from github; and the problem will be solved
The command is :
!python -m pip install git+https://github.com/lopatovsky/HMMs#egg=HMMs

**Comment by SanNicoSan** [comment]
Hello! I'm trying to install another github package:

https://github.com/ismrmrd/ismrmrd-python

After trying to install it with the _**!pip install**_ command, I get the following error:

> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can someone hel me further?

**Comment by yuvipanda** [comment]
Would love to see a release made to PyPI with this patch installed. As of now, installing from PyPI fails with this error for me.

**Comment by agicquel** [comment]
The solution of @medh61 worked for me, with python 3.9.

**Comment by griffinbrookshire** [comment]
Using Python 3.10, had to use: python3 -m pip install git+https://github.com/lopatovsky/HMMs
